### ISSUE TITLE
切号提醒错误

### ISSUE THREAD

**Issue by SonderXiaoming** [othinus001/txcnm#1]
![image](https://user-images.githubusercontent.com/98363578/189464077-b89a4b2f-ed06-489f-b42b-d8cb954312ce.png)
![image](https://user-images.githubusercontent.com/98363578/189464101-0deec03d-b700-4248-bf3e-c95075247b53.png)
虽然切号确实切对了，但是这个提醒错了

**Comment by SonderXiaoming** [comment]
顺带一提，切号之前是不是应该先杀原进程

**Comment by othinus001** [comment]
出现问题的操作方法是？重载一下看看能不能复现，我应该考虑过的。
如果自动要考虑就不叫自动了，会自动杀掉的（虽然杀不杀也无所谓）

**Comment by SonderXiaoming** [comment]
> 出现问题的操作方法是？重载一下看看能不能复现，我应该考虑过的。 如果自动要考虑就不叫自动了，会自动杀掉的（虽然杀不杀也无所谓）

？你没有这种情况嘛，我重载也是一样的。而且我进程确实没杀掉。（难道我配置有问题？）我是windows环境

**Comment by SonderXiaoming** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/98363578/189465144-0adf5cf9-4072-4db6-bfe3-0798e4a90926.png">
这是我config配置

**Comment by othinus001** [comment]
> > 出现问题的操作方法是？重载一下看看能不能复现，我应该考虑过的。 如果自动要考虑就不叫自动了，会自动杀掉的（虽然杀不杀也无所谓）
> 
> ？你没有这种情况嘛，我重载也是一样的。而且我进程确实没杀掉。（难道我配置有问题？）我是windows环境

可以加我qq1280224133看下hoshino和gocq日志，猜测是没成功结束原gocq，同时开了两个？
